// start of controller class

package sample;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.FileChooser;


import java.io.*;
import java.util.Objects;
import java.util.Random;

public class Controller {
    private static boolean existingInputFile = false; // if the user wants to go back to the file
    private boolean isFileRead = false; //first if all we check wether the file is read or not

    @FXML
    private AnchorPane rootPane;
    @FXML
    private TextField numberOfProcessors; // geting the number of processors that the user has chosen
    @FXML
    private Button btnProcess;
    @FXML
    private Button btnChooseFile;
    @FXML
    private Label filePath;

    private void generatefileinput(){ // this is a function that generates  a file
        try {
            FileWriter myWriter = new FileWriter("input.txt");// the file to be generated is called input.txt (generated by file writer)
            Random random = new Random();
            int processesNumber = random.nextInt(100 - 20) + 20; // randomise the number of processesbetween 20 and 100
            int burstsNumber = random.nextInt(20 - 5) + 5; // randomising inputs such as number of bursts
            int[] delay = new int[processesNumber]; // delay helps tell the relativity of the arivall time of the process
            for(int i = 0; i < processesNumber; i++){
                delay[i] = random.nextInt(100 - 20) + 20;
            }
            int[][] cpuBurst = new int[processesNumber][burstsNumber];// calculating  CPU bursts
            int[][] IOBurst = new int[processesNumber][burstsNumber];  // calculating  IO bursts
            for(int i = 0; i < processesNumber; i++){
                for(int j = 0; j < burstsNumber; j++){
                    cpuBurst[i][j] = random.nextInt(120 - 2) + 2;
                    IOBurst[i][j] = random.nextInt(120 - 2) + 2;
                }
            }
            int curr = 0;
            for(int i = 0; i < processesNumber; i++){
                long sum = 0 ;
                Process process = new Process();
                myWriter.write(delay[i]+" ");
                myWriter.write((i+1) + " ");
                process.setArrived(delay[i]+curr);
                process.setDelay(delay[i]);
                process.setPid(i+1);
                curr += delay[i];
                for(int j = 0; j < burstsNumber; j++){
                    myWriter.write(cpuBurst[i][j] + " ");
                    myWriter.write(IOBurst[i][j] + " ");
                    process.insertCPUBurstTime(cpuBurst[i][j]);
                    process.insertIOBurstTime(IOBurst[i][j]);
                    sum += cpuBurst[i][j]+IOBurst[i][j];
                    SimulateController.allCPUBursts += cpuBurst[i][j];
                }
                process.setBurstsSum(sum);
                Process.processes.add(process);
                myWriter.write("\n");
            }
            myWriter.close();
            System.out.println("Successfully wrote to the file.");
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
    private void readFile(String path){
        File file = new File(path); // if the user chose the file
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line; // read the file line by line
            long arrivalForEachProcess = 0;
            while((line = br.readLine()) != null){
                long sum = 0;
                String[] numbers = line.split(" "); // inputs in file must be split by sapce
                if(numbers.length < 4) // 4 digited numbers of bigger are not read
                    continue;
                Process process = new Process();
                arrivalForEachProcess += Long.parseLong(numbers[0]);
                process.setDelay(Integer.parseInt(numbers[0]));
                process.setArrived(arrivalForEachProcess);
                process.setPid(Integer.parseInt(numbers[1]));
                for(int i = 2; i < numbers.length; i++){
                    sum += Integer.parseInt(numbers[i]);
                    SimulateController.allCPUBursts += Integer.parseInt(numbers[i]);
                    process.insertCPUBurstTime(Integer.parseInt(numbers[i++]));
                    process.insertIOBurstTime(Integer.parseInt(numbers[i]));
                    sum += Integer.parseInt(numbers[i]);
                }
                process.setBurstsSum(sum);
                Process.processes.add(process);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void chooseFile(ActionEvent event){
        Process.processes.clear();
        FileChooser fc = new FileChooser();
        fc.getExtensionFilters().addAll(new FileChooser.ExtensionFilter("Text Files", "*.txt"));  // To show only text files.
        File selectedFile = fc.showOpenDialog(null);
        if(selectedFile != null){
            existingInputFile = true;
            readFile(selectedFile.getAbsolutePath());
            isFileRead = true;
            filePath.setText(selectedFile.getAbsolutePath());
            filePath.setAlignment(Pos.CENTER);
        }
        else{
            System.out.println("File Isn't Valid!!!"); // if the file is null or does not follow the rules
        }
    }


    public void nextstep(){ // next step function ( works after the button next step
        try {
             {
                generatefileinput(); // when the button is pressed generate the input file
            }
            String proc = numberOfProcessors.getText(); // check the number of processors
            if(proc == null || proc.length() == 0){ // if the user did not enter a number
                Alert alert = new Alert(Alert.AlertType.WARNING); // pop a warning screen
                alert.setTitle("Error");
                alert.setHeaderText("Missing Value");
                alert.setContentText("Enter number of processors");// make sure that the user enters number of proccesors
                alert.showAndWait();
            }
            else { // if the user did enter the nuber correctly go to the results screen
                int processors = Integer.parseInt(proc);
                SimulateController.setNumberOfProcessors(processors);
                AnchorPane pane = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("simulate.fxml")));
                rootPane.getChildren().setAll(pane);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}